# constants.py

APP_NAME = "AutoTidy"
APP_VERSION = "1.0.1"

# Action types recorded in history
ACTION_MOVED = "MOVED"
ACTION_COPIED = "COPIED"
ACTION_DELETED_TO_TRASH = "DELETED_TO_TRASH"
ACTION_PERMANENTLY_DELETED = "PERMANENTLY_DELETED"
ACTION_SIMULATED_MOVE = "SIMULATED_MOVE"
ACTION_SIMULATED_COPY = "SIMULATED_COPY"
ACTION_SIMULATED_DELETE_TO_TRASH = "SIMULATED_DELETE_TO_TRASH"
ACTION_SIMULATED_PERMANENT_DELETE = "SIMULATED_PERMANENT_DELETE"
ACTION_ERROR = "ERROR"
ACTION_UNDO_MOVE = "UNDO_MOVE"

# Status types recorded in history
STATUS_SUCCESS = "SUCCESS"
STATUS_FAILURE = "FAILURE"
STATUS_SKIPPED = "SKIPPED" # For actions that were intentionally skipped by logic
