name: Build Executables
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip==23.3.2
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Install system dependencies (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libmagic-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install libmagic
          fi
      - name: Build executable
        run: |
          pyinstaller AutoTidy.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/ 
